routes/web.php
<?php

use App\Http\Controllers\LanguageController;

/*
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', [LanguageController::class, 'swap']);

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

app/Models/Product/Product.php
<?php

namespace App\Models\Product;

use Illuminate\Database\Eloquent\Model;
use App\Models\Product\Traits\Attribute\ProductAttribute;
use App\Models\Product\Traits\Relationship\ProductRelationship;

class Product extends Model
{
	use ProductAttribute,
		ProductRelationship;

	protected $table = 'tran_products';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'code',
		'name',
		'category_id',
		'price',
		'active'
	];

	/**
	 * @var array
	 */
	protected $dates = [
		'created_at',
		'updated_at'
	];
}

app/Models/Product/Traits/Attribute/ProductAttribute.php
<?php

namespace App\Models\Product\Traits\Attribute;

/**
 * Trait ProductAttribute.
 */
trait ProductAttribute
{

	/**
	 * @return string
	 */
	public function getStatusLabelAttribute()
	{
		if ($this->active) {
			return "<span class='badge badge-success'>".__('labels.general.active').'</span>';
		}

		return "<span class='badge badge-danger'>".__('labels.general.inactive').'</span>';
	}

	/**
	 * @return string
	 */
	public function getPriceLabelAttribute()
	{
		return $this->price . ' ' .__('strings.general.riel');
	}

	/**
	 * @return string
	 */
	public function getEditButtonAttribute()
	{
		return '<a href="' . route('admin.product.edit', $this->id). '" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
	}

	/**
	 * @return string
	 */
	public function getDeleteButtonAttribute()
	{
		return '<a class="btn btn-danger" href="#"><i class="fas fa-trash"></i></a>';
	}

	/**
	 * @return string
	 */
	public function getActionButtonsAttribute()
	{
		return '
			<div class="btn-group" role="group" aria-label="' . __('labels.backend.access.users.user_actions') . '">
				' . $this->edit_button . '
				' . $this->delete_button . '
			</div>';
	}
}

app/Models/Product/Traits/Relationship/ProductRelationship.php
<?php

namespace App\Models\Product\Traits\Relationship;

use App\Models\Category\Category;
use App\Models\OptionValue\OptionValue;

/**
 * Class ProductRelationship.
 */
trait ProductRelationship
{
	/**
	 * @return mixed
	 */
	public function category()
	{
		return $this->belongsTo(Category::class);
	}

	/**
	 * @return mixed
	 */
	public function option_values()
	{
		return $this->belongsToMany(OptionValue::class, 'tran_product_option', 'product_id', 'option_value_id');
	}

}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Category\Category;
use App\Repositories\CategoryRepository;
use App\Repositories\OptionRepository;
use Illuminate\Http\Request;

/**
 * Class ProductController.
 */
class CategoryController extends Controller
{
	/**
	 * @var CategoryRepository
	 */
	protected $categoryRepository;

	/**
	 * CategoryController constructor.
	 *
	 * @param CategoryRepository $categoryRepository
	 */
	public function __construct(CategoryRepository $categoryRepository)
	{
		$this->categoryRepository = $categoryRepository;
	}

	/**
	 * @return \Illuminate\View\View
	 */
	public function index()
	{
		return view('backend.category.index')
			->withCategories($this->categoryRepository->getCategories());
	}

	/**
	 * @param ManageCategoryRequest    $request
	 *
	 * @return mixed
	 */
	public function create(Request $request, OptionRepository $optionRepository)
	{
		// get all options
		$options = $optionRepository->getOptions()->pluck('name', 'id');

		return view('backend.category.create')
			->withOptions($options);
	}

	/**
	 * @param StoreCategoryRequest $request
	 *
	 * @return mixed
	 * @throws \Throwable
	 */
	public function store(Request $request)
	{
		$this->categoryRepository->create($request->only(
			'name',
			'options'
		));

		return redirect()->route('admin.category.index')->withFlashSuccess(__('alerts.categories.created'));
	}

	/**
	 * @return \Illuminate\View\View
	 */
	public function edit(Category $category, OptionRepository $optionRepository)
	{
		// get all options
		$options = $optionRepository->getOptions()->pluck('name', 'id');

		return view('backend.category.edit')
			->withCategory($category)
			->withOptions($options);
	}

	/**
	 * @param UpdateCategoryRequest $request
	 * @param Category $category
	 *
	 * @return mixed
	 * @throws \App\Exceptions\GeneralException
	 * @throws \Throwable
	 */
	public function update(Request $request, Category $category)
	{
		$this->categoryRepository->update($category, $request->only(
			'name',
			'options'
		));

		return redirect()->route('admin.category.index')->withFlashSuccess(__('alerts.categories.updated'));
	}

	/**
	 * ajax request catewgory changed
	 * @return \Illuminate\View\View
	 */
	public function getOption(Category $category)
	{
		$view = '';
		if ($category) {
			// get option by category_id
			$options = $category->options;

			$view = view('backend.options.value')
				->withOptions($options)
				->render();
		}
			
		return response()->json(['html' => $view], 200);
	}
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/OptionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Option\Option;
use App\Repositories\OptionRepository;

/**
 * Class OptionController.
 */
class OptionController extends Controller
{
		/**
	 * @var OptionRepository
	 */
	protected $optionRepository;

	/**
	 * OptionController constructor.
	 *
	 * @param OptionRepository $optionRepository
	 */
	public function __construct(OptionRepository $optionRepository)
	{
		$this->optionRepository = $optionRepository;
	}
	
	/**
	 * @return \Illuminate\View\View
	 */
	public function index()
	{
		return view('backend.options.index')
			->withOptions($this->optionRepository->getOptions());
	}

	/**
	 * @param ManageCategoryRequest    $request
	 *
	 * @return mixed
	 */
	public function create(Request $request)
	{
		return view('backend.options.create');
	}

	/**
	 * @return \Illuminate\View\View
	 */
	public function store(Request $request)
	{
		$this->optionRepository->create($request->only(
			'name'
		));
		return redirect()->route('admin.option.index')->withFlashSuccess(__('alerts.options.updated'));
	}

	/**
	 * @param Option $option
	 *
	 * @return mixed
	 */
	public function edit(Option $option)
	{		
		return view('backend.options.edit')
			->withOption($option);
	}

	/**
	 * @return mixed
	 * @throws \App\Exceptions\GeneralException
	 * @throws \Throwable
	 */
	public function update(Request $request, Option $option)
	{
		$this->optionRepository->update($option, $request->only(
			'name'
		));

		return redirect()->route('admin.option.index')->withFlashSuccess(__('alerts.options.updated'));
	}
}

app/Http/Controllers/Backend/OptionValueController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Option\Option;
use App\Models\OptionValue\OptionValue;
use App\Repositories\OptionValueRepository;

/**
 * Class OptionValueController.
 */
class OptionValueController extends Controller
{
	/**
	 * @var OptionValueRepository
	 */
	protected $optionValueRepository;

	/**
	 * OptionValueController constructor.
	 *
	 * @param OptionValueRepository $optionValueRepository
	 */
	public function __construct(OptionValueRepository $optionValueRepository)
	{
		$this->optionValueRepository = $optionValueRepository;
	}
	
	/**
	 * @return \Illuminate\View\View
	 */
	public function index(Option $option)
	{
		return view('backend.option_values.index')
			->withOptionId($option->id)
			->withOptionValues($this->optionValueRepository->getOptionValues($option->id));
	}

	/**
	 * @param ManageOptionValueRequest    $request
	 *
	 * @return mixed
	 */
	public function create(Request $request, Option $option)
	{
		return view('backend.option_values.create')
			->withOptionId($option->id);
	}

	/**
	 * @return \Illuminate\View\View
	 */
	public function store(Option $option, Request $request)
	{
		// added array item
		$request->merge(['option_id' => $option->id]);

		$this->optionValueRepository->create($request->only(
			'name',
			'option_id'
		));
		
		return redirect()->route('admin.option.value.index', $option->id)->withFlashSuccess(__('alerts.options.updated'));
	}

	/**
	 * @param Option $option
	 *
	 * @return mixed
	 */
	public function edit(Option $option, OptionValue $optionValue)
	{		
		return view('backend.option_values.edit')
			->withOptionId($option->id)
			->withOptionValue($optionValue);
	}

	/**
	 * @return mixed
	 * @throws \App\Exceptions\GeneralException
	 * @throws \Throwable
	 */
	public function update(Request $request, Option $option, OptionValue $optionValue)
	{
		$this->optionValueRepository->update($optionValue, $request->only(
			'name'
		));

		return redirect()->route('admin.option.value.index', $option->id)->withFlashSuccess(__('alerts.option_values.updated'));
	}
}

app/Http/Controllers/Backend/PaperController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class ProductController.
 */
class PaperController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.paper.index');
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product\Product;
use App\Repositories\CategoryRepository;
use App\Repositories\ProductRepository;
use App\Repositories\OptionRepository;

/**
 * Class ProductController.
 */
class ProductController extends Controller
{
		/**
	 * @var ProductRepository
	 */
	protected $productRepository;

	/**
	 * ProductController constructor.
	 *
	 * @param ProductRepository $productRepository
	 */
	public function __construct(ProductRepository $productRepository)
	{
		$this->productRepository = $productRepository;
	}
	
	/**
	 * @return \Illuminate\View\View
	 */
	public function index(CategoryRepository $categoryRepository)
	{
		$products = $this->productRepository->getAllProducts();

		return view('backend.product.index')
			->withProducts($products);
	}

	/**
	 * @param ManageCategoryRequest    $request
	 *
	 * @return mixed
	 */
	public function create(Request $request, CategoryRepository $categoryRepository, OptionRepository $optionRepository)
	{
		// get all categories
		$categories = $categoryRepository->getCategories();

		// get option by category_id
		$options = $categories[0]->options;

		return view('backend.product.create')
			->withCategories($categories->pluck('name', 'id'))
			->withOptions($options);
	}

	/**
	 * @return \Illuminate\View\View
	 */
	public function store(Request $request)
	{
		$this->productRepository->create($request->only(
			'code',
			'name',
			'category',
			'price',
			'options'
		));
		return redirect()->route('admin.product.index')->withFlashSuccess(__('alerts.products.updated'));
	}

	/**
	 * @param Product $product
	 *
	 * @return mixed
	 */
	public function edit(Product $product, CategoryRepository $categoryRepository)
	{		
		// get all categories
		$categories = $categoryRepository->getCategories();

		// get option by category_id
		$options = $product->category->options;

		// set select value by each other dropdown option value
		$values = $product->option_values->mapWithKeys(function ($values) {
			return [$values->option_id => $values->id];
		});

		return view('backend.product.edit')
			->withProduct($product)
			->withCategories($categories->pluck('name', 'id'))
			->withOptions($options)
			->withValues($values);
	}

	/**
	 * @param UpdateParticipantRequest $request
	 * @param Participant              $participant
	 *
	 * @return mixed
	 * @throws \App\Exceptions\GeneralException
	 * @throws \Throwable
	 */
	public function update(Request $request, Product $product)
	{
		$this->productRepository->update($product, $request->only(
			'code',
			'name',
			'category',
			'price',
			'options'
		));

		return redirect()->route('admin.product.index')->withFlashSuccess(__('alerts.products.updated'));
	}
}

app/Http/Controllers/Frontend/ProductController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product\Product;
use App\Models\Category\Category;
use App\Repositories\ProductRepository;

/**
 * Class ProductController.
 */
class ProductController extends Controller
{
	   /**
	 * @var ProductRepository
	 */
	protected $productRepository;

	/**
	 * ProductController constructor.
	 *
	 * @param ProductRepository $productRepository
	 */
	public function __construct(ProductRepository $productRepository)
	{
		$this->productRepository = $productRepository;
	}

	/**
	 * ajax request productByCategory
	 * @return \Illuminate\View\View
	 */
	// public function productByCategory(Category $category)
	// {
	// 	$view = '';
	// 	if ($category) {
	// 		$products = $this->productRepository->getProductByCategory($category->id);

	// 		$view = view('frontend.products.list')
	// 			->withProducts($products)
	// 			->render();
	// 	}
			
	// 	return response()->json(['html' => $view], 200);
	// }

	/**
	 * ajax request search
	 * @return \Illuminate\View\View
	 */
	public function search(Request $request)
	{
		$view = '';
		// if ($category) {
			$products = $this->productRepository->getProductByFilter($request->only(
				'category',
				'options'
			));

			$view = view('frontend.products.list')
				->withProducts($products)
				->render();
		// }
			
		return response()->json(['html' => $view], 200);
	}
}

resources/views/backend/product/create.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('strings.backend.product.title'))

@section('content')
{{ html()->form('POST', route('admin.product.store'))->class('form-horizontal')->open() }}
	<div class="card">
		<div class="card-header">
			@lang('strings.products.management')<span class="text-muted"> | @lang('labels.general.create')</span>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="form-group col-sm-3">
					{{ html()->label('Code')->class('form-control-label')->for('code') }}
					{{ html()->text('code')
						->class('form-control')
					}}
				</div>
				<div class="form-group col-sm-5">
					{{ html()->label('Name')->class('form-control-label')->for('name') }}
					{{ html()->text('name')
						->class('form-control')
					}}
				</div>
				<div class="form-group col-sm-4">
					<label for="company">Image</label><br>
					<input id="file-input" type="file" name="file-input">
				</div>
			</div>
			<div class="row">
				<div class="form-group col-sm-3">
					{{ html()->label('Category')->class('form-control-label')->for('category') }}
					{{ html()->select('category')
						->class('form-control')
						->options($categories)
					}}
				</div>

				<div class="col-sm-9">
					<div id="optionValue">@include('backend.options.value')</div>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-sm-3">
					{{ html()->label('Price')->class('form-control-label')->for('price') }}
					{{ html()->text('price')
						->class('form-control')
					}}
				</div>
			</div>
		</div>
		<div class="card-footer text-right">
			{{ form_cancel(route('admin.product.index'), '<i class="fas fa-ban"></i> ' . __('buttons.general.cancel'), ['btn btn-danger btn-min']) }}
			{{ form_submit('<i class="far fa-save"></i> ' . __('buttons.general.save'), ['btn btn-success btn-min']) }}
		</div>
	</div>
{{ html()->form()->close() }}
@endsection

@push('after-scripts')
<script type="text/javascript">
	$(function () {
		$('#category').change(function () {
			$.ajax({
				type: 'GET',
				url: '{{ url("admin/category") }}/' + $(this).val() + '/option',
				success: function (res) {
					$('#optionValue').html(res.html);
				},
				error: function (res) {
					console.log('An error occurred.');
				},
			});
		});
	});
</script>
@endpush

resources/views/backend/product/edit.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('strings.backend.dashboard.title'))

@section('content')
{{ html()->modelForm($product, 'PATCH', route('admin.product.update', $product->id))->class('form-horizontal')->open() }}
<div class="card">
	<div class="card-header">
		@lang('strings.products.management')<span class="text-muted"> | @lang('labels.general.edit')</span>
	</div>
	<div class="card-body">
		<div class="row">
			<div class="form-group col-sm-3">
				{{ html()->label('Code')->class('form-control-label')->for('code') }}
				{{ html()->text('code')
					->class('form-control')
				}}
			</div>
			<div class="form-group col-sm-5">
				{{ html()->label('Name')->class('form-control-label')->for('name') }}
				{{ html()->text('name')
					->class('form-control')
				}}
			</div>
			<div class="form-group col-sm-4">
				<label for="company">Image</label><br>
				<input id="file-input" type="file" name="file-input">
			</div>
		</div>
		<div class="row">
			<div class="form-group col-sm-3">
				{{ html()->label('Category')->class('form-control-label')->for('category') }}
				{{ html()->select('category')
					->class('form-control')
					->options($categories)
					->value($product->category_id)
				}}
			</div>

			<div class="form-group col-sm-9">
				<div id="optionValue">@include('backend.options.value')</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-sm-3">
				{{ html()->label('Price')->class('form-control-label')->for('price') }}
				{{ html()->text('price')
					->class('form-control')
				}}
			</div>
		</div>
	</div>
	<div class="card-footer text-right">
		{{ form_cancel(route('admin.product.index'), '<i class="fas fa-ban"></i> ' . __('buttons.general.cancel'), ['btn btn-danger btn-min']) }}
		{{ form_submit('<i class="far fa-save"></i> ' . __('buttons.general.save'), ['btn btn-success btn-min']) }}
	</div>
</div>
{{ html()->closeModelForm() }}


@endsection

resources/views/backend/product/index.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('strings.backend.dashboard.title'))

@section('content')
<div class="card">
	<div class="card-header">
		<i class="fa fa-edit"></i> @lang('strings.products.management')
		<div class="float-right">
			<a href="{{ route('admin.product.create') }}" class="btn btn-sm btn-success"><i class="fas fa-plus"></i> @lang('buttons.general.crud.create')</a>
		</div>
	</div>
	<div class="card-body">
		<table class="table table-striped table-bordered datatable">
			<thead>
				<tr class="text-center">
					<th>@lang('labels.products.tables.numbering')</th>
					<th>@lang('labels.products.tables.code')</th>
					<th class="text-left">@lang('labels.products.tables.name')</th>
					<th class="text-left">@lang('labels.products.tables.category')</th>
					<th class="text-right">@lang('labels.products.tables.price')</th>
					<th>@lang('labels.products.tables.status')</th>
					<th>@lang('labels.products.tables.action')</th>
				</tr>
			</thead>
			<tbody>
				@foreach($products as $product)
					<tr class="text-center">
						<td>{{ $loop->iteration }}</td>
						<td>{{ $product->code }}</td>
						<td class="text-left">{{ $product->name }}</td>
						<td class="text-left">{{ $product->category->name }}</td>
						<td class="text-right">{{ $product->price_label }}</td>
						<td>{!! $product->status_label !!}</td>
						<td>{!! $product->action_buttons !!}</td>
					</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>
@endsection

@push('after-scripts')
<script type="text/javascript">
	$(function () {
		$('#category').change(function () {
			{{-- ajax action --}}
			$.ajax({
				type: 'GET',
				url: '{{ url("admin/category") }}' + '/' + $(this).val() + '/get',
				success: function (res) {
					$('#type').html(res.html);
				}
			});
		});
	});
</script>
@endpush()